version: '3.8'

services:
  # Neon Local Proxy for development
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: ccdcca2-neon-local
    ports:
      - "5432:5432"
    env_file:
      - ./.env.development
    volumes:
      # Persistent branch per Git branch (optional)
      - ./.neon_local/:/tmp/.neon_local
      - ./.git/HEAD:/tmp/.git/HEAD:ro
    networks:
      - ccdcca2-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5432"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ccdcca2-app-dev
    ports:
      - "3000:3000"
    env_file:
      - ./.env.development
    volumes:
      # Mount source code for hot reloading in development
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      # Mount logs directory for persistence
      - ./logs:/app/logs
    depends_on:
      neon-local:
        condition: service_healthy
    networks:
      - ccdcca2-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "const http=require('http');http.get('http://localhost:3000/health',(r)=>{process.exit(r.statusCode===200?0:1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ccdcca2-network:
    driver: bridge

volumes:
  neon_local_data:
    driver: local
